### ISSUE TITLE
S3 Integration for audio file storage

### ISSUE THREAD

**Issue by jponto** [GenderPerformance/gender-performance#17]
**User Story**: 
* As a user, I want to be able to maintain a record of my audio recordings to support history
* As a developer, I want to be able to easily access recordings from multiple services

---

**Description**
One option for storing our audio is in a cloud storage solution like Amazon S3. This will allow persistent access to the files our users record

**Tasks**

- [x] Set up S3 bucket
- [x] Enable upload from frontend on record
- [x] Enable authentication in express routes
- [ ] Enable download of file into test.py file

**Test Cases**
